name: cover

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: test-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            test-${{ runner.os }}-go-
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with coverage
        run: go test -race -v -coverpkg=./... -coverprofile=profile.out ./... && go tool cover -func profile.out

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: profile.out
          if-no-files-found: error
          retention-days: 1

      - name: Send coverage
        uses: codecov/codecov-action@v3
        with:
          file: profile.out

  send:
    runs-on: ubuntu-latest
    needs:
      - run
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Send coverage
        uses: codecov/codecov-action@v3
        with:
          file: profile.out